### ISSUE TITLE
Feed not working after deployment

### ISSUE THREAD

**Issue by lottaar** [igorsuhinin/modx-instagram-latest-posts#1]
The Instagram feed was working fine on localhost, but after deploying the site to my web host the page with the feed gives an http 500 error. In the server log i get this, not sure if it's related:

` mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '[' in /var/www/vhosts/mydomain.com/core/cache/includes/elements/modsnippet/81.include.cache.php on line 53
`

I've cleared the core/cache folder and also tried just a basic call like this with no luck:
```
[[!InstagramLatestPosts?
          &accountName=`nike` &cacheEnabled=`0`
]]
```

**Comment by igorsuhinin** [comment]
Well, this issue can be related to the old PHP version. Starting from PHP 5.4.0 it's allowed to use short array syntax like $a = [1,2,3] instead of $a = array(1, 2, 3);

What is the PHP version on your web server? If it's lower than PHP 5.4 then it's time to upgrade :) Or you can manually replace all arrays from [] to array().

**Comment by lottaar** [comment]
I was on PHP 5.3.3 but after upgrading to 7 it works perfectly. Many thanks for your quick help and an awesome module!

**Comment by igorsuhinin** [comment]
You are welcome ;)
