### ISSUE TITLE
Error: The JSON parsing failed

### ISSUE THREAD

**Issue by Onixarts** [igorsuhinin/modx-instagram-latest-posts#14]
Hi, Just installed the extra 1.8.1 in modx and getting error The JSON parsing failed.
In https://github.com/igorsuhinin/modx-instagram-latest-posts/blob/01214645d173888492d9eb8a37b11e119de50067/snippet.php#L126 there is a user->media, but in JSON returned from Instagram, there is no media object in user.

**Comment by igorsuhinin** [comment]
Hi,

Can you provide me the username which you are using to get the data from
Instagram? I need to see the result. You can send me it by email which you
can find it the snippet.

Thanks,
Igor

13 марта 2018 г. 11:36 PM пользователь "Onixarts" <notifications@github.com>
написал:

Hi, Just installed the extra 1.8.1 in modx and getting error The JSON
parsing failed.
In https://github.com/igorsuhinin/modx-instagram-latest-posts/blob/
01214645d173888492d9eb8a37b11e119de50067/snippet.php#L126 there is a
user->media, but in JSON returned from Instagram, there is no media object
in user.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/igorsuhinin/modx-instagram-latest-posts/issues/14>, or mute
the thread

**Comment by ajilderda** [comment]
This also goes for our username: `angi_studio`. Thanks for this extra!

**Comment by Onixarts** [comment]
user onixarts :)

**Comment by igorsuhinin** [comment]
Guys, looks like Instagram has changed their data structure again :/
It will take some time when I am able to fix this. Currently I'm too busy with other projects.

**Comment by itsmerobliberty** [comment]
the updated json in this pull snippet works https://github.com/igorsuhinin/modx-instagram-latest-posts/pull/15

**Comment by igorsuhinin** [comment]
Thanks, guys, for your contributing! You are great :)
 I've just released a new version where these updates are included.
