### ISSUE TITLE
Добавить больше информации с инсты

### ISSUE THREAD

**Issue by makc9I** [igorsuhinin/modx-instagram-latest-posts#4]
Хотелось бы получать дополнительную информацию, такую как количество просмотров, лайков, а также описание к фото. Будет ли это реализовано?

**Comment by igorsuhinin** [comment]
В принципе да, это реально сделать. Займусь в свободное время, но быстро не могу обещать :)

**Comment by c0mat0se** [comment]
I would love this feature too! Any progress?

**Comment by igorsuhinin** [comment]
Hi @c0mat0se,
What do you mean about THIS feature? Which one? :) Instagram returns a lot of additional information... So I'm just not sure if it is reasonable to add all of them in the parameters.

**Comment by igorsuhinin** [comment]
Just look at this https://codebeautify.org/jsonviewer/cb4a0a28. It's a huge JSON response with a lot of data. Sure all this can be added to the snippet but it looks like too much for me.

**Comment by c0mat0se** [comment]
Hi @igorsuhinin.  I think pulling in likes for each post would be the only thing I would want added.

**Comment by igorsuhinin** [comment]
I see. OK, I think I will add it soon :) Btw, you can do it yourself if you know PHP well enough. It's really easy if you are able to read the code.

**Comment by c0mat0se** [comment]
Awesome, thank you! I could probably add it myself, but then any update to the extra will override my code.

**Comment by igorsuhinin** [comment]
If you can do it yourself you can always send me a PR (Pull Request) as
others did and I will accept it. So the next updates will contain your
changes as well.

30 янв. 2018 г. 1:22 AM пользователь "Sargasm" <notifications@github.com>
написал:

Awesome, thank you! I could probably add it myself, but then any update to
the extra will override my code.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/igorsuhinin/modx-instagram-latest-posts/issues/4#issuecomment-361421831>,
or mute the thread

**Comment by igorsuhinin** [comment]
Thanks, @c0mat0se :)
Your PR is included in the source code. Later I will send the update for MODX Extra as well.

**Comment by igorsuhinin** [comment]
Closed with the release https://github.com/igorsuhinin/modx-instagram-latest-posts/tree/v1.7.0
